extends RefCounted
class_name FishingUpgradeDB

const DATA_PATH := "res://Data/FishingUpgradeData.json"
const EXTRA_FAMILY_ORDER: Array[String] = ["ECON", "DENS", "SURV", "MOVE", "POWR", "ACTV", "BOSS", "TEAM"]
const EXTRA_NAME_A: Array[String] = ["Adaptive", "Fractal", "Iron", "Solar", "Echo", "Rift", "Pulse", "Aegis", "Vector", "Nova"]
const EXTRA_NAME_B: Array[String] = ["Circuit", "Relay", "Ledger", "Spine", "Burst", "Anchor", "Lattice", "Compass", "Engine", "Matrix"]
const HERO_CORE_TIERS_PER_NODE := 5
const HERO_SPEED_NODE_BONUS: Array[float] = [0.04, 0.08, 0.12, 0.24]
const HERO_DAMAGE_NODE_PCT: Array[int] = [36, 52, 68, 84]
const FAMILY_DESCRIPTIONS := {
    "ECON": "UPGRADE_DB_FAMILY_ECON",
    "DENS": "UPGRADE_DB_FAMILY_DENS",
    "SURV": "UPGRADE_DB_FAMILY_SURV",
    "MOVE": "UPGRADE_DB_FAMILY_MOVE",
    "POWR": "UPGRADE_DB_FAMILY_PWR",
    "ACTV": "UPGRADE_DB_FAMILY_ACTV",
    "BOSS": "UPGRADE_DB_FAMILY_BOSS",
    "TEAM": "UPGRADE_DB_FAMILY_TEAM",
}
const SPECIFIC_DESCRIPTIONS := {
    "cursor_pickup_unlock": "UPGRADE_DB_DESCRIPTION_CURSOR_PICKUP_UNLOCK",
    "recruit_archer": "UPGRADE_DB_DESCRIPTION_RECRUIT_ARCHER",
    "auto_attack_unlock": "UPGRADE_DB_DESCRIPTION_AUTO_ATTACK_UNLOCK",
    "battle_speed_unlock_2x": "UPGRADE_DB_DESCRIPTION_BATTLE_SPEED_2X",
    "battle_speed_unlock_4x": "UPGRADE_DB_DESCRIPTION_BATTLE_SPEED_4X",
    "battle_speed_unlock_8x": "UPGRADE_DB_DESCRIPTION_BATTLE_SPEED_8X",
    "old_art_unlock": "UPGRADE_DB_DESCRIPTION_OLD_ART_UNLOCK",
    "knight_vamp_unlock": "UPGRADE_DB_DESCRIPTION_KNIGHT_VAMP_UNLOCK",
    "archer_pierce_unlock": "UPGRADE_DB_DESCRIPTION_ARCHER_PIERCE_UNLOCK",
    "power_harvest_unlock": "UPGRADE_DB_DESCRIPTION_POWER_HARVEST_UNLOCK",
    "recruit_guardian": "UPGRADE_DB_DESCRIPTION_RECRUIT_GUARDIAN",
    "guardian_fortify_unlock": "UPGRADE_DB_DESCRIPTION_GUARDIAN_FORTIFY_UNLOCK",
    "recruit_mage": "UPGRADE_DB_DESCRIPTION_RECRUIT_MAGE",
    "mage_storm_unlock": "UPGRADE_DB_DESCRIPTION_MAGE_STORM_UNLOCK",
    "party_damage_boost": "UPGRADE_DB_DESCRIPTION_PARTY_DAMAGE_08",
    "party_battle_standard": "UPGRADE_DB_DESCRIPTION_PARTY_DAMAGE_12",
    "party_war_drums": "UPGRADE_DB_DESCRIPTION_PARTY_DAMAGE_16",
    "party_execution_doctrine": "UPGRADE_DB_DESCRIPTION_PARTY_DAMAGE_20",
    "party_apex_overdrive": "UPGRADE_DB_DESCRIPTION_PARTY_DAMAGE_25",
    "vitality_foundation": "UPGRADE_DB_DESCRIPTION_VITALITY_FOUNDATION",
}
const SPECIFIC_NAMES := {
    "cursor_pickup_unlock": "UPGRADE_DB_NAME_CURSOR_PICKUP_UNLOCK",
    "recruit_archer": "UPGRADE_DB_NAME_RECRUIT_ARCHER",
    "auto_attack_unlock": "UPGRADE_DB_NAME_AUTO_ATTACK_UNLOCK",
    "battle_speed_unlock_2x": "UPGRADE_DB_NAME_BATTLE_SPEED_UNLOCK_2X",
    "battle_speed_unlock_4x": "UPGRADE_DB_NAME_BATTLE_SPEED_UNLOCK_4X",
    "battle_speed_unlock_8x": "UPGRADE_DB_NAME_BATTLE_SPEED_UNLOCK_8X",
    "old_art_unlock": "UPGRADE_DB_NAME_OLD_ART_UNLOCK",
    "knight_vamp_unlock": "UPGRADE_DB_NAME_KNIGHT_VAMP_UNLOCK",
    "archer_pierce_unlock": "UPGRADE_DB_NAME_ARCHER_PIERCE_UNLOCK",
    "power_harvest_unlock": "UPGRADE_DB_NAME_POWER_HARVEST_UNLOCK",
    "recruit_guardian": "UPGRADE_DB_NAME_RECRUIT_GUARDIAN",
    "guardian_fortify_unlock": "UPGRADE_DB_NAME_GUARDIAN_FORTIFY_UNLOCK",
    "recruit_mage": "UPGRADE_DB_NAME_RECRUIT_MAGE",
    "mage_storm_unlock": "UPGRADE_DB_NAME_MAGE_STORM_UNLOCK",
    "party_damage_boost": "UPGRADE_DB_NAME_PARTY_DAMAGE_BOOST",
    "party_battle_standard": "UPGRADE_DB_NAME_PARTY_BATTLE_STANDARD",
    "party_war_drums": "UPGRADE_DB_NAME_PARTY_WAR_DRUMS",
    "party_execution_doctrine": "UPGRADE_DB_NAME_PARTY_EXECUTION_DOCTRINE",
    "party_apex_overdrive": "UPGRADE_DB_NAME_PARTY_APEX_OVERDRIVE",
    "vitality_foundation": "UPGRADE_DB_NAME_VITALITY_FOUNDATION",
}

var nodes: Array[Dictionary] = []
var node_by_id: Dictionary = {}
var sim_notes_by_id: Dictionary = {}
static var _cached_data: Dictionary = {}

func _trf(key: String, args: Array = []) -> String:
    var translated: String = tr(key)
    return translated % args if not args.is_empty() else translated

func _init(data_override: Variant = null) -> void:
    var data: Variant = data_override
    if not (data is Dictionary):
        data = get_cached_data()
    if data == null:
        return
    var arr = data.get("upgrades", [])
    for item in arr:
        var node: Dictionary = item
        node = node.duplicate(true)
        node["icon"] = _resolve_icon(node)
        nodes.append(node)
        node_by_id[node.get("id", "")] = node

    # Editor-only simulation annotation support.
    # When present, this file is generated by upgrade-effectiveness simulation tools.
    if OS.has_feature("editor"):
        var sim_path: String = "res://simulation/3_2_2026_20_Sims/upgrade_effectiveness.json"
        var raw_sim: String = ""
        if FileAccess.file_exists(sim_path):
            raw_sim = FileAccess.get_file_as_string(sim_path)
        if raw_sim != "":
            var parsed_sim = JSON.parse_string(raw_sim)
            if parsed_sim is Dictionary:
                var dict_sim: Dictionary = parsed_sim
                var rows_variant: Variant = dict_sim.get("upgrades", [])
                if rows_variant is Array:
                    for row_variant in rows_variant:
                        if not (row_variant is Dictionary):
                            continue
                        var row: Dictionary = row_variant
                        var row_id: String = str(row.get("id", ""))
                        if row_id == "":
                            continue
                        sim_notes_by_id[row_id] = row

static func clear_cached_data() -> void:
    _cached_data = {}

static func get_cached_data() -> Dictionary:
    if _cached_data.is_empty():
        var loaded: Variant = Util.load_json_data_from_path(DATA_PATH)
        if loaded is Dictionary:
            _cached_data = loaded
    return _cached_data

static func is_removed_tactical_telemetry_upgrade_key(key: String) -> bool:
    if key == "core_density":
        return true
    if key.begins_with("extra_skill_"):
        var index: int = int(key.trim_prefix("extra_skill_"))
        if index > 0:
            var family: int = posmod(index - 1, EXTRA_FAMILY_ORDER.size())
            return family == 1 or family == 3

    var lower_key: String = key.to_lower()
    return _is_removed_walk_speed_key(lower_key) or _is_removed_enemy_count_key(lower_key)

static func _is_removed_walk_speed_key(lower_key: String) -> bool:
    return lower_key.find("trail") != -1 \
        or lower_key.find("stride") != -1 \
        or lower_key.find("route") != -1 \
        or lower_key.find("pathline") != -1 \
        or lower_key.find("quickstep") != -1 \
        or lower_key.find("momentum") != -1 \
        or lower_key.find("march") != -1 \
        or lower_key.find("sprint") != -1

static func _is_removed_enemy_count_key(lower_key: String) -> bool:
    return lower_key.find("horde") != -1 \
        or lower_key.find("wave") != -1 \
        or lower_key.find("crowd") != -1 \
        or lower_key.find("pressure") != -1

static func _filter_removed_tactical_telemetry_upgrades(data: Dictionary) -> Dictionary:
    var filtered: Dictionary = data.duplicate(true)
    var upgrades_variant: Variant = filtered.get("upgrades", [])
    if not (upgrades_variant is Array):
        return filtered

    var upgrades: Array = upgrades_variant
    var children_by_id: Dictionary = {}
    for entry_variant in upgrades:
        if not (entry_variant is Dictionary):
            continue
        var entry: Dictionary = entry_variant
        var dep_id: String = str(entry.get("dependency", ""))
        var entry_id: String = str(entry.get("id", ""))
        if dep_id == "" or entry_id == "":
            continue
        if not children_by_id.has(dep_id):
            children_by_id[dep_id] = []
        var child_ids: Array = children_by_id[dep_id]
        child_ids.append(entry_id)
        children_by_id[dep_id] = child_ids

    var tactical_descendants: Dictionary = {}
    var frontier: Array[String] = ["auto_attack_unlock"]
    while not frontier.is_empty():
        var current_id: String = frontier.pop_back()
        var child_variants: Array = children_by_id.get(current_id, [])
        for child_variant in child_variants:
            var child_id: String = str(child_variant)
            if tactical_descendants.has(child_id):
                continue
            tactical_descendants[child_id] = true
            frontier.append(child_id)

    var removed_ids: Dictionary = {}
    var removed_parent_by_id: Dictionary = {}
    for entry_variant in upgrades:
        if not (entry_variant is Dictionary):
            continue
        var entry: Dictionary = entry_variant
        var entry_id: String = str(entry.get("id", ""))
        var key: String = str(entry.get("key", ""))
        if not tactical_descendants.has(entry_id):
            continue
        if not is_removed_tactical_telemetry_upgrade_key(key):
            continue
        removed_ids[entry_id] = true
        removed_parent_by_id[entry_id] = str(entry.get("dependency", ""))

    var sanitized_upgrades: Array[Dictionary] = []
    for entry_variant in upgrades:
        if not (entry_variant is Dictionary):
            continue
        var entry: Dictionary = entry_variant
        var entry_id: String = str(entry.get("id", ""))
        if removed_ids.has(entry_id):
            continue

        var sanitized_entry: Dictionary = entry.duplicate(true)
        var dep_id: String = str(sanitized_entry.get("dependency", ""))
        while dep_id != "" and removed_ids.has(dep_id):
            dep_id = str(removed_parent_by_id.get(dep_id, ""))
        sanitized_entry["dependency"] = dep_id if dep_id != "" else null
        sanitized_upgrades.append(sanitized_entry)

    filtered["upgrades"] = sanitized_upgrades
    filtered["total_nodes"] = sanitized_upgrades.size()
    return filtered

func is_owned(node: Dictionary) -> bool:
    return SaveHandler.get_fishing_upgrade_level(str(node.get("key", ""))) >= int(node.get("level", 1))

func is_dependency_met(node: Dictionary) -> bool:
    var dep_id: String = str(node.get("dependency", ""))
    if dep_id == "":
        return true
    if not node_by_id.has(dep_id):
        return true
    return is_owned(node_by_id[dep_id])

func can_buy(node: Dictionary) -> bool:
    if is_owned(node):
        return false
    if not is_dependency_met(node):
        return false
    var key: String = str(node.get("key", ""))
    var target_level: int = int(node.get("level", 1))
    var current_level: int = SaveHandler.get_fishing_upgrade_level(key)
    if target_level != current_level + 1:
        return false
    return SaveHandler.fishing_currency >= int(round(float(node.get("cost", 0.0))))

func buy(node: Dictionary) -> bool:
    if not can_buy(node):
        return false
    var cost: int = int(round(float(node.get("cost", 0.0))))
    SaveHandler.fishing_currency = max(0, SaveHandler.fishing_currency - cost)
    var key: String = str(node.get("key", ""))
    var repeatable: bool = bool(node.get("repeatable", false))
    SaveHandler.unlock_fishing_upgrade(key, repeatable)
    SaveHandler.save_fishing_progress()
    return true

func get_display_name(node: Dictionary) -> String:
    var key: String = str(node.get("key", ""))
    var level: int = int(node.get("level", 1))

    if key == "hero_coin_gain":
        return _trf("UPGRADE_DB_NAME_HERO_COIN_GAIN", [_roman((level - 1) / 5 + 1)])
    if key == "cursor_capture_gain":
        return _trf("UPGRADE_DB_NAME_CURSOR_CAPTURE", [_roman((level - 1) / 5 + 1)])
    if key == "vitality_hitpoints":
        return _trf("UPGRADE_DB_NAME_VITALITY_HITPOINTS", [_roman((level - 1) / 5 + 1)])
    if key == "vitality_power":
        return _trf("UPGRADE_DB_NAME_VITALITY_POWER", [_roman((level - 1) / 5 + 1)])
    if key == "vitality_channel":
        return _trf("UPGRADE_DB_NAME_VITALITY_CHANNEL", [_roman((level - 1) / 5 + 1)])
    if SPECIFIC_NAMES.has(key):
        return tr(SPECIFIC_NAMES[key])
    if key.begins_with("extra_skill_"):
        return _extra_skill_name(key)
    if key.begins_with("core_"):
        return _core_name(key, level)

    var clean_key: String = key
    if clean_key.ends_with("_60"):
        clean_key = clean_key.trim_suffix("_60")
    var display_name: String = _humanize_name(clean_key)
    if level > 1 and not display_name.ends_with(_roman(level)):
        display_name += " " + _roman(level)
    return display_name

func get_description(node: Dictionary) -> String:
    var explicit_description: String = str(node.get("description", "")).strip_edges()
    if explicit_description != "":
        return _with_editor_note(node, explicit_description)

    var key: String = str(node.get("key", ""))
    if key == "battle_speed_unlock_2x":
        return _with_editor_note(node, tr("UPGRADE_DB_DESCRIPTION_BATTLE_SPEED_2X"))
    if key == "battle_speed_unlock_4x":
        return _with_editor_note(node, tr("UPGRADE_DB_DESCRIPTION_BATTLE_SPEED_4X"))
    if key == "battle_speed_unlock_8x":
        return _with_editor_note(node, tr("UPGRADE_DB_DESCRIPTION_BATTLE_SPEED_8X"))
    if key == "old_art_unlock":
        return _with_editor_note(node, tr("UPGRADE_DB_DESCRIPTION_OLD_ART_UNLOCK"))
    if key == "hero_coin_gain":
        return _with_editor_note(node, tr("UPGRADE_DB_DESCRIPTION_HERO_COIN_GAIN"))
    if key == "cursor_capture_gain":
        return _with_editor_note(node, tr("UPGRADE_DB_DESCRIPTION_CURSOR_CAPTURE_GAIN"))
    if key == "vitality_hitpoints":
        return _with_editor_note(node, tr("UPGRADE_DB_DESCRIPTION_VITALITY_HITPOINTS"))
    if key == "vitality_power":
        return _with_editor_note(node, tr("UPGRADE_DB_DESCRIPTION_VITALITY_POWER"))
    if key == "vitality_channel":
        return _with_editor_note(node, tr("UPGRADE_DB_DESCRIPTION_VITALITY_CHANNEL"))
    if SPECIFIC_DESCRIPTIONS.has(key):
        return _with_editor_note(node, tr(SPECIFIC_DESCRIPTIONS[key]))

    if key.begins_with("core_"):
        return _with_editor_note(node, _describe_core_upgrade(node))
    if key.begins_with("extra_skill_"):
        return _with_editor_note(node, _describe_extra_skill(key))

    var specific_effect: String = _describe_key_effect(key)
    if specific_effect != "":
        return _with_editor_note(node, specific_effect)

    var family_desc: String = _infer_family_description(key)
    if family_desc != "":
        return _with_editor_note(node, tr(family_desc))

    return _with_editor_note(
        node,
        tr("UPGRADE_DB_DESCRIPTION_FALLBACK")
    )

func _with_editor_note(node: Dictionary, base: String) -> String:
    if not OS.has_feature("editor"):
        return base
    var node_id: String = str(node.get("id", ""))
    if node_id == "" or not sim_notes_by_id.has(node_id):
        return base
    var note: Dictionary = sim_notes_by_id[node_id]
    var dk: float = float(note.get("delta_kills_per_run", 0.0))
    var dc: float = float(note.get("delta_coins_per_run", 0.0))
    var run_ref: int = int(note.get("run_index", 0))
    var editor_line: String = "[Editor] Sim delta (run %d): %+0.2f kills/run, %+0.1f coins/run." % [
        run_ref,
        dk,
        dc,
    ]
    return "%s\n\n%s" % [base, editor_line]

func _describe_core_upgrade(node: Dictionary) -> String:
    var key: String = str(node.get("key", ""))
    var level: int = int(node.get("level", 1))
    if key == "core_armor":
        return tr("UPGRADE_DB_DESCRIPTION_CORE_ARMOR")
    if key.begins_with("core_armor_enemy_"):
        var enemy_track: int = int(key.trim_prefix("core_armor_enemy_"))
        var enemy_per_level_block: int = int(pow(4, enemy_track))
        return _trf("UPGRADE_DB_DESCRIPTION_CORE_ARMOR_ENEMY", [enemy_per_level_block])
    if key.begins_with("core_armor_dot_"):
        var track: int = int(key.trim_prefix("core_armor_dot_"))
        var per_level_block: int = 0
        match track:
            1:
                per_level_block = 3
            2:
                per_level_block = 9
            3:
                per_level_block = 27
            4:
                per_level_block = 81
        return _trf("UPGRADE_DB_DESCRIPTION_CORE_ARMOR_DOT", [per_level_block])
    if key.begins_with("core_armor_boss_"):
        var boss_track: int = int(key.trim_prefix("core_armor_boss_"))
        var boss_per_level_block: int = 0
        match boss_track:
            1:
                boss_per_level_block = 25
            2:
                boss_per_level_block = 100
            3:
                boss_per_level_block = 400
            4:
                boss_per_level_block = 1600
            5:
                boss_per_level_block = 10750
        return _trf("UPGRADE_DB_DESCRIPTION_CORE_ARMOR_BOSS", [boss_per_level_block, boss_per_level_block * 5])
    if key == "core_density":
        return tr("UPGRADE_DB_DESCRIPTION_CORE_DENSITY")
    if key == "core_drop":
        return tr("UPGRADE_DB_DESCRIPTION_CORE_DROP")
    if key == "core_power":
        return tr("UPGRADE_DB_DESCRIPTION_CORE_POWER")
    if key == "party_damage_boost":
        return tr("UPGRADE_DB_DESCRIPTION_PARTY_DAMAGE_08")

    var hero_name: String = _hero_core_name(key)
    if hero_name != "":
        var node_index: int = _hero_core_node_index(level)
        if key.find("damage") != -1:
            var pct: int = HERO_DAMAGE_NODE_PCT[node_index]
            var tier_start: int = node_index * HERO_CORE_TIERS_PER_NODE + 1
            var tier_end: int = tier_start + HERO_CORE_TIERS_PER_NODE - 1
            return _trf("UPGRADE_DB_DESCRIPTION_HERO_DAMAGE_TIERS", [
                tier_start,
                tier_end,
                pct,
                hero_name,
                1.0 + float(pct) / 100.0,
            ])
        if key.find("speed") != -1:
            var speed_bonus: float = HERO_SPEED_NODE_BONUS[node_index]
            var tier_start_speed: int = node_index * HERO_CORE_TIERS_PER_NODE + 1
            var tier_end_speed: int = tier_start_speed + HERO_CORE_TIERS_PER_NODE - 1
            return _trf("UPGRADE_DB_DESCRIPTION_HERO_SPEED_TIERS", [
                tier_start_speed,
                tier_end_speed,
                speed_bonus,
                hero_name,
                speed_bonus * HERO_CORE_TIERS_PER_NODE,
            ])

    return _trf("UPGRADE_DB_DESCRIPTION_CORE_STAT_LEVEL", [level])

func _describe_extra_skill(key: String) -> String:
    var family: String = _extra_skill_family(key)
    match family:
        "ECON":
            return tr("UPGRADE_DB_DESCRIPTION_EXTRA_SKILL_ECON")
        "DENS":
            return tr("UPGRADE_DB_DESCRIPTION_EXTRA_SKILL_DENS")
        "SURV":
            return tr("UPGRADE_DB_DESCRIPTION_EXTRA_SKILL_SURV")
        "MOVE":
            return tr("UPGRADE_DB_DESCRIPTION_EXTRA_SKILL_MOVE")
        "POWR":
            return tr("UPGRADE_DB_DESCRIPTION_EXTRA_SKILL_PWR")
        "ACTV":
            return tr("UPGRADE_DB_DESCRIPTION_EXTRA_SKILL_ACTV")
        "BOSS":
            return tr("UPGRADE_DB_DESCRIPTION_EXTRA_SKILL_BOSS")
        "TEAM":
            return tr("UPGRADE_DB_DESCRIPTION_EXTRA_SKILL_TEAM")
        _:
            return tr("UPGRADE_DB_DESCRIPTION_FALLBACK")

func _describe_key_effect(key: String) -> String:
    var lower: String = key.to_lower()
    if lower.find("party_damage_boost") >= 0:
        return tr("UPGRADE_DB_DESCRIPTION_PARTY_DAMAGE_08")
    if lower.find("party_battle_standard") >= 0:
        return tr("UPGRADE_DB_DESCRIPTION_PARTY_DAMAGE_12")
    if lower.find("party_war_drums") >= 0:
        return tr("UPGRADE_DB_DESCRIPTION_PARTY_DAMAGE_16")
    if lower.find("party_execution_doctrine") >= 0:
        return tr("UPGRADE_DB_DESCRIPTION_PARTY_DAMAGE_20")
    if lower.find("party_apex_overdrive") >= 0:
        return tr("UPGRADE_DB_DESCRIPTION_PARTY_DAMAGE_25")
    if lower.find("damage") >= 0:
        return tr("UPGRADE_DB_DESCRIPTION_KEY_DAMAGE")
    if lower.find("speed") >= 0 or lower.find("cadence") >= 0:
        return tr("UPGRADE_DB_DESCRIPTION_KEY_SPEED")
    if lower.find("armor") >= 0 or lower.find("plate") >= 0 or lower.find("fortify") >= 0 or lower.find("hemostasis") >= 0:
        return tr("UPGRADE_DB_DESCRIPTION_KEY_ARMOR")
    if lower.find("power") >= 0 or lower.find("reservoir") >= 0 or lower.find("invocation") >= 0 or lower.find("active") >= 0:
        return tr("UPGRADE_DB_DESCRIPTION_KEY_POWER")
    if lower.find("boss") >= 0 or lower.find("segment") >= 0:
        return tr("UPGRADE_DB_DESCRIPTION_KEY_BOSS")
    if lower.find("drop") >= 0 or lower.find("pickup") >= 0 or lower.find("coin") >= 0 or lower.find("salvage") >= 0:
        return tr("UPGRADE_DB_DESCRIPTION_KEY_COIN")
    if lower.find("density") >= 0 or lower.find("horde") >= 0 or lower.find("wave") >= 0 or lower.find("crowd") >= 0:
        return tr("UPGRADE_DB_DESCRIPTION_KEY_DENSITY")
    if lower.find("move") >= 0 or lower.find("march") >= 0 or lower.find("sprint") >= 0 or lower.find("route") >= 0:
        return tr("UPGRADE_DB_DESCRIPTION_FAMILY_MOVE")
    if lower.find("lens") >= 0 or lower.find("magnet") >= 0 or lower.find("cursor") >= 0:
        return tr("UPGRADE_DB_DESCRIPTION_FAMILY_CURSOR")
    if lower.find("archer") >= 0 or lower.find("knight") >= 0 or lower.find("guardian") >= 0 or lower.find("mage") >= 0:
        return tr("UPGRADE_DB_DESCRIPTION_FAMILY_HERO")
    return ""

func _extra_skill_family(key: String) -> String:
    var n: int = int(key.trim_prefix("extra_skill_"))
    if n <= 0:
        return "TEAM"
    return EXTRA_FAMILY_ORDER[(n - 1) % EXTRA_FAMILY_ORDER.size()]

func _infer_family_description(key: String) -> String:
    if key.find("boss") != -1:
        return FAMILY_DESCRIPTIONS["BOSS"]
    if key.find("active") != -1 or key.find("invocation") != -1 or key.find("channel") != -1 or key.find("cadence") != -1:
        return FAMILY_DESCRIPTIONS["ACTV"]
    if key.find("power") != -1 or key.find("condensed") != -1 or key.find("reservoir") != -1 or key.find("echo") != -1:
        return FAMILY_DESCRIPTIONS["POWR"]
    if key.find("drop") != -1 or key.find("salvage") != -1 or key.find("market") != -1 or key.find("scanner") != -1 or key.find("collector") != -1:
        return FAMILY_DESCRIPTIONS["ECON"]
    if key.find("horde") != -1 or key.find("pressure") != -1 or key.find("wave") != -1 or key.find("crowd") != -1:
        return FAMILY_DESCRIPTIONS["DENS"]
    if key.find("armor") != -1 or key.find("plate") != -1 or key.find("carapace") != -1 or key.find("shock") != -1 or key.find("hemostasis") != -1:
        return FAMILY_DESCRIPTIONS["SURV"]
    if key.find("boot") != -1 or key.find("stride") != -1 or key.find("route") != -1 or key.find("quickstep") != -1 or key.find("march") != -1 or key.find("sprint") != -1:
        return FAMILY_DESCRIPTIONS["MOVE"]
    if key.find("knight") != -1 or key.find("archer") != -1 or key.find("guardian") != -1 or key.find("mage") != -1:
        return FAMILY_DESCRIPTIONS["TEAM"]
    return ""

func _armor_purchase_amounts(start_level: int, purchase_count: int, armor_type: String) -> Array[int]:
    var amounts: Array[int] = []
    for i in range(max(0, purchase_count)):
        var current_level: int = start_level + i
        if current_level <= 0:
            continue
        var amount: int = 0
        match armor_type:
            "enemy":
                amount = int(pow(4, current_level))
            "boss":
                amount = int(25 * pow(4, current_level - 1))
            _:
                amount = int(pow(3, current_level))
        amounts.append(amount)
    return amounts

func _join_int_list(values: Array[int]) -> String:
    if values.is_empty():
        return "0"
    var text_values: PackedStringArray = []
    for value in values:
        text_values.append(str(value))
    if text_values.size() == 1:
        return text_values[0]
    if text_values.size() == 2:
        return "%s and %s" % [text_values[0], text_values[1]]
    var last_value: String = text_values[text_values.size() - 1]
    text_values.remove_at(text_values.size() - 1)
    return "%s, and %s" % [", ".join(text_values), last_value]

func _humanize_name(name_text: String) -> String:
    var text: String = name_text.strip_edges()
    if text == "":
        return "Upgrade"
    text = text.to_lower().replace("_", " ")
    var words: PackedStringArray = text.split(" ", false)
    for i in range(words.size()):
        if words[i].length() <= 0:
            continue
        words[i] = words[i].substr(0, 1).to_upper() + words[i].substr(1)
    return " ".join(words)

func _resolve_icon(node: Dictionary) -> String:
    var raw_icon: String = str(node.get("icon", "")).strip_edges()
    if raw_icon != "" and raw_icon != "?":
        return raw_icon
    return _fallback_icon_for_key(str(node.get("key", "")))

func _fallback_icon_for_key(key: String) -> String:
    var lower: String = key.to_lower()
    if lower.begins_with("core_"):
        return "C"
    if lower.begins_with("extra_skill_"):
        var family: String = _extra_skill_family(lower)
        match family:
            "ECON":
                return "E"
            "DENS":
                return "D"
            "SURV":
                return "S"
            "MOVE":
                return "M"
            "POWR":
                return "P"
            "ACTV":
                return "A"
            "BOSS":
                return "B"
            _:
                return "T"
    if lower.begins_with("recruit_"):
        return "H"
    if lower.find("boss") != -1:
        return "B"
    if lower.find("power") != -1 or lower.find("active") != -1:
        return "P"
    if lower.find("armor") != -1 or lower.find("plate") != -1 or lower.find("fortify") != -1:
        return "S"
    if lower.find("drop") != -1 or lower.find("coin") != -1 or lower.find("salvage") != -1 or lower.find("magnet") != -1:
        return "E"
    if lower.find("damage") != -1 or lower.find("speed") != -1:
        return "D"
    var fallback: String = lower.strip_edges()
    if fallback == "":
        return "U"
    return fallback.substr(0, 1).to_upper()

func _extra_skill_name(key: String) -> String:
    var n: int = int(key.trim_prefix("extra_skill_"))
    if n <= 0:
        return tr("UPGRADE_DB_NAME_EXTRA_SKILL_FALLBACK")
    var idx: int = (n - 1) % EXTRA_NAME_A.size()
    return _trf("UPGRADE_DB_NAME_EXTRA_SKILL", [EXTRA_NAME_A[idx], EXTRA_NAME_B[idx], n])

func _core_name(key: String, level: int = 1) -> String:
    if key == "core_armor":
        return tr("UPGRADE_DB_NAME_CORE_ARMOR")
    if key.begins_with("core_armor_enemy_"):
        var track: int = int(key.trim_prefix("core_armor_enemy_"))
        return _trf("UPGRADE_DB_NAME_CONTACT_ARMOR", [_roman(track)])
    if key.begins_with("core_armor_dot_"):
        var track: int = int(key.trim_prefix("core_armor_dot_"))
        return _trf("UPGRADE_DB_NAME_DOT_ARMOR", [_roman(track)])
    if key.begins_with("core_armor_boss_"):
        var track: int = int(key.trim_prefix("core_armor_boss_"))
        return _trf("UPGRADE_DB_NAME_BOSS_ARMOR", [_roman(track)])
    if key == "core_density":
        return tr("UPGRADE_DB_NAME_CORE_DENSITY")
    if key == "core_drop":
        return tr("UPGRADE_DB_NAME_CORE_DROP")
    if key == "core_power":
        return tr("UPGRADE_DB_NAME_CORE_POWER")
    var hero_name: String = _hero_core_name(key)
    if hero_name != "":
        var node_tier: String = _roman(_hero_core_node_index(level) + 1)
        if key.find("damage") != -1:
            return _trf("UPGRADE_DB_NAME_HERO_DAMAGE", [hero_name, node_tier])
        if key.find("speed") != -1:
            return _trf("UPGRADE_DB_NAME_HERO_SPEED", [hero_name, node_tier])
    if key.find("knight") != -1 and key.find("damage") != -1:
        return tr("UPGRADE_DB_NAME_CORE_KNIGHT_DAMAGE")
    if key.find("knight") != -1 and key.find("speed") != -1:
        return tr("UPGRADE_DB_NAME_CORE_KNIGHT_SPEED")
    if key.find("knight") != -1 and key.find("active_cap") != -1:
        return tr("UPGRADE_DB_NAME_CORE_KNIGHT_ACTIVE_CAP")
    if key.find("archer") != -1 and key.find("damage") != -1:
        return tr("UPGRADE_DB_NAME_CORE_ARCHER_DAMAGE")
    if key.find("archer") != -1 and key.find("speed") != -1:
        return tr("UPGRADE_DB_NAME_CORE_ARCHER_SPEED")
    if key.find("archer") != -1 and key.find("active_cap") != -1:
        return tr("UPGRADE_DB_NAME_CORE_ARCHER_ACTIVE_CAP")
    if key.find("guardian") != -1 and key.find("damage") != -1:
        return tr("UPGRADE_DB_NAME_CORE_GUARDIAN_DAMAGE")
    if key.find("guardian") != -1 and key.find("speed") != -1:
        return tr("UPGRADE_DB_NAME_CORE_GUARDIAN_SPEED")
    if key.find("guardian") != -1 and key.find("active_cap") != -1:
        return tr("UPGRADE_DB_NAME_CORE_GUARDIAN_ACTIVE_CAP")
    if key.find("mage") != -1 and key.find("damage") != -1:
        return tr("UPGRADE_DB_NAME_CORE_MAGE_DAMAGE")
    if key.find("mage") != -1 and key.find("speed") != -1:
        return tr("UPGRADE_DB_NAME_CORE_MAGE_SPEED")
    if key.find("mage") != -1 and key.find("active_cap") != -1:
        return tr("UPGRADE_DB_NAME_CORE_MAGE_ACTIVE_CAP")
    return _humanize_name(key)

func _hero_core_name(key: String) -> String:
    if key.find("knight") != -1:
        return tr("BATTLE_SOURCE_KNIGHT")
    if key.find("archer") != -1:
        return tr("BATTLE_SOURCE_ARCHER")
    if key.find("guardian") != -1:
        return tr("BATTLE_SOURCE_GUARDIAN")
    if key.find("mage") != -1:
        return tr("BATTLE_SOURCE_MAGE")
    return ""

func _hero_core_node_index(level: int) -> int:
    return clampi((max(level, 1) - 1) / HERO_CORE_TIERS_PER_NODE, 0, HERO_DAMAGE_NODE_PCT.size() - 1)

func _roman(value: int) -> String:
    match value:
        1:
            return "I"
        2:
            return "II"
        3:
            return "III"
        4:
            return "IV"
        5:
            return "V"
        6:
            return "VI"
        7:
            return "VII"
        8:
            return "VIII"
        9:
            return "IX"
        10:
            return "X"
        _:
            return str(value)
