extends RefCounted
class_name FishingUpgradeDB

const DATA_PATH := "res://Data/FishingUpgradeData.json"
const EXTRA_FAMILY_ORDER: Array[String] = ["ECON", "DENS", "SURV", "MOVE", "POWR", "ACTV", "BOSS", "TEAM"]
const EXTRA_NAME_A: Array[String] = ["Adaptive", "Fractal", "Iron", "Solar", "Echo", "Rift", "Pulse", "Aegis", "Vector", "Nova"]
const EXTRA_NAME_B: Array[String] = ["Circuit", "Relay", "Ledger", "Spine", "Burst", "Anchor", "Lattice", "Compass", "Engine", "Matrix"]
const HERO_CORE_TIERS_PER_NODE := 5
const HERO_SPEED_NODE_BONUS: Array[float] = [0.04, 0.08, 0.12, 0.24]
const HERO_DAMAGE_NODE_PCT: Array[int] = [36, 52, 68, 84]
const FAMILY_DESCRIPTIONS := {
    "ECON": "Improves income conversion and pickup efficiency.",
    "DENS": "Increases enemy pressure to raise total reward ceiling.",
    "SURV": "Improves survivability and run depth.",
    "MOVE": "Improves traversal tempo.",
    "POWR": "Improves power economy for actives.",
    "ACTV": "Improves active ability uptime.",
    "BOSS": "Improves boss phase output, safety, or rewards.",
    "TEAM": "Improves hero-specific combat synergy.",
}
const SPECIFIC_DESCRIPTIONS := {
    "cursor_pickup_unlock": "Unlocks cursor pickup bonuses so cursor-collected coins are worth more.",
    "recruit_archer": "Adds the Archer hero to your combat lineup.",
    "auto_attack_unlock": "Unlocks Tactical Telemetry: reveals enemies remaining during battle using the blue progress HUD.",
    "battle_speed_unlock_2x": "Unlocks 2x battle speed in non-editor builds.",
    "battle_speed_unlock_4x": "Unlocks 4x battle speed in non-editor builds.",
    "battle_speed_unlock_8x": "Unlocks 8x battle speed in non-editor builds.",
    "old_art_unlock": "Reveals the Art: Old/New toggle in release builds. Cosmetic only; no gameplay effect.",
    "knight_vamp_unlock": "Unlocks the Knight active and improves life steal sustain.",
    "archer_pierce_unlock": "Unlocks the Archer active with piercing attack coverage.",
    "power_harvest_unlock": "Unlocks stronger power generation from combat and pickups.",
    "recruit_guardian": "Adds the Guardian hero to your combat lineup.",
    "guardian_fortify_unlock": "Unlocks the Guardian active: grants a Limited-Time Fortify that reduces incoming damage.",
    "recruit_mage": "Adds the Mage hero to your combat lineup.",
    "mage_storm_unlock": "Unlocks the Mage active: while active, the storm repeatedly damages all enemies on screen.",
    "party_damage_boost": "Increases all party damage by 8% per level.",
    "party_battle_standard": "Increases all party damage by 12% per level.",
    "party_war_drums": "Increases all party damage by 16% per level.",
    "party_execution_doctrine": "Increases all party damage by 20% per level.",
    "party_apex_overdrive": "Increases all party damage by 25% per level.",
    "vitality_foundation": "Unlocks the Vitality tree: +50 max Health. From here you can invest in Hitpoints, Power, or Channel time.",
}
const SPECIFIC_NAMES := {
    "cursor_pickup_unlock": "Cursor Pickup Unlock",
    "recruit_archer": "Recruit Archer",
    "auto_attack_unlock": "Tactical Telemetry",
    "battle_speed_unlock_2x": "Temportal Throttle",
    "battle_speed_unlock_4x": "Temportal Throttle II",
    "battle_speed_unlock_8x": "Temportal Throttle III",
    "old_art_unlock": "Archive of First Light",
    "knight_vamp_unlock": "Knight Vampirism Unlock",
    "archer_pierce_unlock": "Archer Pierce Unlock",
    "power_harvest_unlock": "Power Harvest Unlock",
    "recruit_guardian": "Recruit Guardian",
    "guardian_fortify_unlock": "Guardian Fortify Unlock",
    "recruit_mage": "Recruit Mage",
    "mage_storm_unlock": "Mage Storm Unlock",
    "party_damage_boost": "Party Power",
    "party_battle_standard": "Battle Standard",
    "party_war_drums": "War Drums",
    "party_execution_doctrine": "Execution Doctrine",
    "party_apex_overdrive": "Apex Overdrive",
    "vitality_foundation": "Vitality Foundation",
}

var nodes: Array[Dictionary] = []
var node_by_id: Dictionary = {}
var sim_notes_by_id: Dictionary = {}
static var _cached_data: Dictionary = {}

func _init(data_override: Variant = null) -> void:
    var data: Variant = data_override
    if not (data is Dictionary):
        data = get_cached_data()
    if data == null:
        return
    var arr = data.get("upgrades", [])
    for item in arr:
        var node: Dictionary = item
        node = node.duplicate(true)
        node["icon"] = _resolve_icon(node)
        nodes.append(node)
        node_by_id[node.get("id", "")] = node

    # Editor-only simulation annotation support.
    # When present, this file is generated by upgrade-effectiveness simulation tools.
    if OS.has_feature("editor"):
        var sim_path: String = "res://simulation/3_2_2026_20_Sims/upgrade_effectiveness.json"
        var raw_sim: String = ""
        if FileAccess.file_exists(sim_path):
            raw_sim = FileAccess.get_file_as_string(sim_path)
        if raw_sim != "":
            var parsed_sim = JSON.parse_string(raw_sim)
            if parsed_sim is Dictionary:
                var dict_sim: Dictionary = parsed_sim
                var rows_variant: Variant = dict_sim.get("upgrades", [])
                if rows_variant is Array:
                    for row_variant in rows_variant:
                        if not (row_variant is Dictionary):
                            continue
                        var row: Dictionary = row_variant
                        var row_id: String = str(row.get("id", ""))
                        if row_id == "":
                            continue
                        sim_notes_by_id[row_id] = row

static func clear_cached_data() -> void:
    _cached_data = {}

static func get_cached_data() -> Dictionary:
    if _cached_data.is_empty():
        var loaded: Variant = Util.load_json_data_from_path(DATA_PATH)
        if loaded is Dictionary:
            _cached_data = loaded
    return _cached_data

static func is_removed_tactical_telemetry_upgrade_key(key: String) -> bool:
    if key == "core_density":
        return true
    if key.begins_with("extra_skill_"):
        var index: int = int(key.trim_prefix("extra_skill_"))
        if index > 0:
            var family: int = posmod(index - 1, EXTRA_FAMILY_ORDER.size())
            return family == 1 or family == 3

    var lower_key: String = key.to_lower()
    return _is_removed_walk_speed_key(lower_key) or _is_removed_enemy_count_key(lower_key)

static func _is_removed_walk_speed_key(lower_key: String) -> bool:
    return lower_key.find("trail") != -1 \
        or lower_key.find("stride") != -1 \
        or lower_key.find("route") != -1 \
        or lower_key.find("pathline") != -1 \
        or lower_key.find("quickstep") != -1 \
        or lower_key.find("momentum") != -1 \
        or lower_key.find("march") != -1 \
        or lower_key.find("sprint") != -1

static func _is_removed_enemy_count_key(lower_key: String) -> bool:
    return lower_key.find("horde") != -1 \
        or lower_key.find("wave") != -1 \
        or lower_key.find("crowd") != -1 \
        or lower_key.find("pressure") != -1

static func _filter_removed_tactical_telemetry_upgrades(data: Dictionary) -> Dictionary:
    var filtered: Dictionary = data.duplicate(true)
    var upgrades_variant: Variant = filtered.get("upgrades", [])
    if not (upgrades_variant is Array):
        return filtered

    var upgrades: Array = upgrades_variant
    var children_by_id: Dictionary = {}
    for entry_variant in upgrades:
        if not (entry_variant is Dictionary):
            continue
        var entry: Dictionary = entry_variant
        var dep_id: String = str(entry.get("dependency", ""))
        var entry_id: String = str(entry.get("id", ""))
        if dep_id == "" or entry_id == "":
            continue
        if not children_by_id.has(dep_id):
            children_by_id[dep_id] = []
        var child_ids: Array = children_by_id[dep_id]
        child_ids.append(entry_id)
        children_by_id[dep_id] = child_ids

    var tactical_descendants: Dictionary = {}
    var frontier: Array[String] = ["auto_attack_unlock"]
    while not frontier.is_empty():
        var current_id: String = frontier.pop_back()
        var child_variants: Array = children_by_id.get(current_id, [])
        for child_variant in child_variants:
            var child_id: String = str(child_variant)
            if tactical_descendants.has(child_id):
                continue
            tactical_descendants[child_id] = true
            frontier.append(child_id)

    var removed_ids: Dictionary = {}
    var removed_parent_by_id: Dictionary = {}
    for entry_variant in upgrades:
        if not (entry_variant is Dictionary):
            continue
        var entry: Dictionary = entry_variant
        var entry_id: String = str(entry.get("id", ""))
        var key: String = str(entry.get("key", ""))
        if not tactical_descendants.has(entry_id):
            continue
        if not is_removed_tactical_telemetry_upgrade_key(key):
            continue
        removed_ids[entry_id] = true
        removed_parent_by_id[entry_id] = str(entry.get("dependency", ""))

    var sanitized_upgrades: Array[Dictionary] = []
    for entry_variant in upgrades:
        if not (entry_variant is Dictionary):
            continue
        var entry: Dictionary = entry_variant
        var entry_id: String = str(entry.get("id", ""))
        if removed_ids.has(entry_id):
            continue

        var sanitized_entry: Dictionary = entry.duplicate(true)
        var dep_id: String = str(sanitized_entry.get("dependency", ""))
        while dep_id != "" and removed_ids.has(dep_id):
            dep_id = str(removed_parent_by_id.get(dep_id, ""))
        sanitized_entry["dependency"] = dep_id if dep_id != "" else null
        sanitized_upgrades.append(sanitized_entry)

    filtered["upgrades"] = sanitized_upgrades
    filtered["total_nodes"] = sanitized_upgrades.size()
    return filtered

func is_owned(node: Dictionary) -> bool:
    return SaveHandler.get_fishing_upgrade_level(str(node.get("key", ""))) >= int(node.get("level", 1))

func is_dependency_met(node: Dictionary) -> bool:
    var dep_id: String = str(node.get("dependency", ""))
    if dep_id == "":
        return true
    if not node_by_id.has(dep_id):
        return true
    return is_owned(node_by_id[dep_id])

func can_buy(node: Dictionary) -> bool:
    if is_owned(node):
        return false
    if not is_dependency_met(node):
        return false
    var key: String = str(node.get("key", ""))
    var target_level: int = int(node.get("level", 1))
    var current_level: int = SaveHandler.get_fishing_upgrade_level(key)
    if target_level != current_level + 1:
        return false
    return SaveHandler.fishing_currency >= int(round(float(node.get("cost", 0.0))))

func buy(node: Dictionary) -> bool:
    if not can_buy(node):
        return false
    var cost: int = int(round(float(node.get("cost", 0.0))))
    SaveHandler.fishing_currency = max(0, SaveHandler.fishing_currency - cost)
    var key: String = str(node.get("key", ""))
    var repeatable: bool = bool(node.get("repeatable", false))
    SaveHandler.unlock_fishing_upgrade(key, repeatable)
    SaveHandler.save_fishing_progress()
    return true

func get_display_name(node: Dictionary) -> String:
    var key: String = str(node.get("key", ""))
    var level: int = int(node.get("level", 1))

    if key == "hero_coin_gain":
        return "Hero Coin Gain " + _roman((level - 1) / 5 + 1)
    if key == "cursor_capture_gain":
        return "Cursor Capture " + _roman((level - 1) / 5 + 1)
    if key == "vitality_hitpoints":
        return "Vitality Hitpoints " + _roman((level - 1) / 5 + 1)
    if key == "vitality_power":
        return "Vitality Power " + _roman((level - 1) / 5 + 1)
    if key == "vitality_channel":
        return "Vitality Channel " + _roman((level - 1) / 5 + 1)
    if SPECIFIC_NAMES.has(key):
        return SPECIFIC_NAMES[key]
    if key.begins_with("extra_skill_"):
        return _extra_skill_name(key)
    if key.begins_with("core_"):
        return _core_name(key, level)

    var clean_key: String = key
    if clean_key.ends_with("_60"):
        clean_key = clean_key.trim_suffix("_60")
    var display_name: String = _humanize_name(clean_key)
    if level > 1 and not display_name.ends_with(_roman(level)):
        display_name += " " + _roman(level)
    return display_name

func get_description(node: Dictionary) -> String:
    var explicit_description: String = str(node.get("description", "")).strip_edges()
    if explicit_description != "":
        return _with_editor_note(node, explicit_description)

    var key: String = str(node.get("key", ""))
    if key == "battle_speed_unlock_2x":
        return _with_editor_note(node, "Unlocks the Speed button and enables 2x battle speed.")
    if key == "battle_speed_unlock_4x":
        return _with_editor_note(node, "Unlocks 4x battle speed.")
    if key == "battle_speed_unlock_8x":
        return _with_editor_note(node, "Unlocks 8x battle speed.")
    if key == "old_art_unlock":
        return _with_editor_note(node, "Reveals the Art: Old/New toggle in release builds. Cosmetic only; no gameplay effect.")
    if key == "hero_coin_gain":
        return _with_editor_note(node, "Multiplies coin value by +6% per level (exponential over 20 levels). Applies to coins collected by heroes or cursor.")
    if key == "cursor_capture_gain":
        return _with_editor_note(node, "Multiplies cursor-captured coin value by +2.5% per level (exponential over 25 levels).")
    if key == "vitality_hitpoints":
        return _with_editor_note(node, "Increases max Health by 20% per level. Each of the five tracks (I–V) adds 20% per level; cost scales 3x per track depth. Stacks multiplicatively across all levels.")
    if key == "vitality_power":
        return _with_editor_note(node, "Increases power generation and power capacity by 5% per level. Each of the five tracks (I–V) adds 5% per level; cost scales 3x per track depth.")
    if key == "vitality_channel":
        return _with_editor_note(node, "Increases active ability channel (duration) by 5% per level, active power cost by 5% per level, and power charged per hero click by 5% per level. Lets actives run longer at a higher activation cost without increasing clicks to cast. Cost scales 3x per track depth.")
    if SPECIFIC_DESCRIPTIONS.has(key):
        return _with_editor_note(node, SPECIFIC_DESCRIPTIONS[key])

    if key.begins_with("core_"):
        return _with_editor_note(node, _describe_core_upgrade(node))
    if key.begins_with("extra_skill_"):
        return _with_editor_note(node, _describe_extra_skill(key))

    var specific_effect: String = _describe_key_effect(key)
    if specific_effect != "":
        return _with_editor_note(node, specific_effect)

    var family_desc: String = _infer_family_description(key)
    if family_desc != "":
        return _with_editor_note(node, family_desc)

    return _with_editor_note(
        node,
        "Improves run combat effectiveness by boosting hero output, uptime, durability, or reward conversion on this branch."
    )

func _with_editor_note(node: Dictionary, base: String) -> String:
    if not OS.has_feature("editor"):
        return base
    var node_id: String = str(node.get("id", ""))
    if node_id == "" or not sim_notes_by_id.has(node_id):
        return base
    var note: Dictionary = sim_notes_by_id[node_id]
    var dk: float = float(note.get("delta_kills_per_run", 0.0))
    var dc: float = float(note.get("delta_coins_per_run", 0.0))
    var run_ref: int = int(note.get("run_index", 0))
    var editor_line: String = "[Editor] Sim delta (run %d): %+0.2f kills/run, %+0.1f coins/run." % [
        run_ref,
        dk,
        dc,
    ]
    return "%s\n\n%s" % [base, editor_line]

func _describe_core_upgrade(node: Dictionary) -> String:
    var key: String = str(node.get("key", ""))
    var level: int = int(node.get("level", 1))
    if key == "core_armor":
        return "Unlocks the Core Armor branch: three paths that reduce enemy, DOT, and boss damage taken. Armor can prevent at most 90% of damage taken."
    if key.begins_with("core_armor_enemy_"):
        var enemy_track: int = int(key.trim_prefix("core_armor_enemy_"))
        var enemy_per_level_block: int = int(pow(4, enemy_track))
        return "Reduces regular enemy contact damage by %d." % enemy_per_level_block
    if key.begins_with("core_armor_dot_"):
        var track: int = int(key.trim_prefix("core_armor_dot_"))
        var per_level_block: int = 0
        match track:
            1:
                per_level_block = 3
            2:
                per_level_block = 9
            3:
                per_level_block = 27
            4:
                per_level_block = 81
        return "Reduces damage-over-time by %d damage per second." % per_level_block
    if key.begins_with("core_armor_boss_"):
        var boss_track: int = int(key.trim_prefix("core_armor_boss_"))
        var boss_per_level_block: int = 0
        match boss_track:
            1:
                boss_per_level_block = 25
            2:
                boss_per_level_block = 100
            3:
                boss_per_level_block = 400
            4:
                boss_per_level_block = 1600
            5:
                boss_per_level_block = 10750
        return "Blocks %d boss contact damage per purchase in this node, %d total when fully upgraded." % [boss_per_level_block, boss_per_level_block * 5]
    if key == "core_density":
        return "Increase enemy density by ~5% per level (and coin rewards by ~2% per level) for higher potential rewards."
    if key == "core_drop":
        return "Increase coin drop value scaling by +8% per level."
    if key == "core_power":
        return "Increase power gain by +12% per level, power cap by +8, and reduce active power cost by about 2% per level."
    if key == "party_damage_boost":
        return "Increase all party damage by 8% per level."

    var hero_name: String = _hero_core_name(key)
    if hero_name != "":
        var node_index: int = _hero_core_node_index(level)
        if key.find("damage") != -1:
            var pct: int = HERO_DAMAGE_NODE_PCT[node_index]
            var tier_start: int = node_index * HERO_CORE_TIERS_PER_NODE + 1
            var tier_end: int = tier_start + HERO_CORE_TIERS_PER_NODE - 1
            return "Tiers %d-%d: +%d%% %s damage per purchase (x%.2f each buy). Full branch exceeds 10000x base damage." % [
                tier_start,
                tier_end,
                pct,
                hero_name,
                1.0 + float(pct) / 100.0,
            ]
        if key.find("speed") != -1:
            var speed_bonus: float = HERO_SPEED_NODE_BONUS[node_index]
            var tier_start_speed: int = node_index * HERO_CORE_TIERS_PER_NODE + 1
            var tier_end_speed: int = tier_start_speed + HERO_CORE_TIERS_PER_NODE - 1
            return "Tiers %d-%d: +%.2f attacks/sec for %s per purchase (+%.2f attacks/sec across this node). Full branch reaches 3.00x base attack rate." % [
                tier_start_speed,
                tier_end_speed,
                speed_bonus,
                hero_name,
                speed_bonus * HERO_CORE_TIERS_PER_NODE,
            ]

    return "Increase this core stat scaling (Level %d)." % level

func _describe_extra_skill(key: String) -> String:
    var family: String = _extra_skill_family(key)
    match family:
        "ECON":
            return "Increases combat reward efficiency so each kill converts into more useful coin and stronger next-run upgrades."
        "DENS":
            return "Raises enemy density/pressure so your DPS kills more targets per second and increases coin-per-minute ceiling."
        "SURV":
            return "Improves survivability (armor/contact/DoT mitigation) so the team survives deeper waves and reaches bosses more often."
        "MOVE":
            return "Improves formation movement and retarget tempo so heroes spend less time repositioning and more time dealing damage."
        "POWR":
            return "Improves power generation/cap/refund so actives trigger earlier and more frequently in each run."
        "ACTV":
            return "Improves active uptime (duration and cooldown cadence), increasing burst windows and sustained team DPS."
        "BOSS":
            return "Improves boss-phase effectiveness (damage throughput, mitigation, or reward scaling) to clear more boss segments."
        "TEAM":
            return "Improves hero-specific combat stats and active ceilings, increasing total squad damage and consistency."
        _:
            return "Boosts combat scaling for this branch and improves clear speed against enemies and boss phases."

func _describe_key_effect(key: String) -> String:
    var lower: String = key.to_lower()
    if lower.find("party_damage_boost") >= 0:
        return "Increases all party damage by 8% per level."
    if lower.find("party_battle_standard") >= 0:
        return "Increases all party damage by 12% per level."
    if lower.find("party_war_drums") >= 0:
        return "Increases all party damage by 16% per level."
    if lower.find("party_execution_doctrine") >= 0:
        return "Increases all party damage by 20% per level."
    if lower.find("party_apex_overdrive") >= 0:
        return "Increases all party damage by 25% per level."
    if lower.find("damage") >= 0:
        return "Increases direct damage output (typically about +1.2%–1.5% total team DPS per level before global tuning)."
    if lower.find("speed") >= 0 or lower.find("cadence") >= 0:
        return "Increases attack cadence (typically about +0.9%–1.2% faster attacks per level before global tuning)."
    if lower.find("armor") >= 0 or lower.find("plate") >= 0 or lower.find("fortify") >= 0 or lower.find("hemostasis") >= 0:
        return "Reduces incoming damage (roughly -0.8% to -1.2% taken per level before global tuning)."
    if lower.find("power") >= 0 or lower.find("reservoir") >= 0 or lower.find("invocation") >= 0 or lower.find("active") >= 0:
        return "Improves active ability economy (about +2.5% power gain per level and modest cooldown/cost reductions before global tuning)."
    if lower.find("boss") >= 0 or lower.find("segment") >= 0:
        return "Improves boss progression (reduces effective boss HP or increases boss rewards by a few percent per level)."
    if lower.find("drop") >= 0 or lower.find("pickup") >= 0 or lower.find("coin") >= 0 or lower.find("salvage") >= 0:
        return "Increases coin conversion from combat by roughly +3% income per level (before cursor and extra-skill bonuses)."
    if lower.find("density") >= 0 or lower.find("horde") >= 0 or lower.find("wave") >= 0 or lower.find("crowd") >= 0:
        return "Increases enemy density by a few percent per level so high DPS builds can secure more kills (and coins) per minute."
    if lower.find("move") >= 0 or lower.find("march") >= 0 or lower.find("sprint") >= 0 or lower.find("route") >= 0:
        return "Improves combat pacing (roughly +1%–1.5% frontline walk speed per level) to reduce downtime between engagements."
    if lower.find("lens") >= 0 or lower.find("magnet") >= 0 or lower.find("cursor") >= 0:
        return "Increases cursor-collected coin value by about +5% per level, stacking with other coin multipliers."
    if lower.find("archer") >= 0 or lower.find("knight") >= 0 or lower.find("guardian") >= 0 or lower.find("mage") >= 0:
        return "Improves hero-specific combat contribution (roughly +1%–2% total squad DPS or safety per level depending on the hero)."
    return ""

func _extra_skill_family(key: String) -> String:
    var n: int = int(key.trim_prefix("extra_skill_"))
    if n <= 0:
        return "TEAM"
    return EXTRA_FAMILY_ORDER[(n - 1) % EXTRA_FAMILY_ORDER.size()]

func _infer_family_description(key: String) -> String:
    if key.find("boss") != -1:
        return FAMILY_DESCRIPTIONS["BOSS"]
    if key.find("active") != -1 or key.find("invocation") != -1 or key.find("channel") != -1 or key.find("cadence") != -1:
        return FAMILY_DESCRIPTIONS["ACTV"]
    if key.find("power") != -1 or key.find("condensed") != -1 or key.find("reservoir") != -1 or key.find("echo") != -1:
        return FAMILY_DESCRIPTIONS["POWR"]
    if key.find("drop") != -1 or key.find("salvage") != -1 or key.find("market") != -1 or key.find("scanner") != -1 or key.find("collector") != -1:
        return FAMILY_DESCRIPTIONS["ECON"]
    if key.find("horde") != -1 or key.find("pressure") != -1 or key.find("wave") != -1 or key.find("crowd") != -1:
        return FAMILY_DESCRIPTIONS["DENS"]
    if key.find("armor") != -1 or key.find("plate") != -1 or key.find("carapace") != -1 or key.find("shock") != -1 or key.find("hemostasis") != -1:
        return FAMILY_DESCRIPTIONS["SURV"]
    if key.find("boot") != -1 or key.find("stride") != -1 or key.find("route") != -1 or key.find("quickstep") != -1 or key.find("march") != -1 or key.find("sprint") != -1:
        return FAMILY_DESCRIPTIONS["MOVE"]
    if key.find("knight") != -1 or key.find("archer") != -1 or key.find("guardian") != -1 or key.find("mage") != -1:
        return FAMILY_DESCRIPTIONS["TEAM"]
    return ""

func _armor_purchase_amounts(start_level: int, purchase_count: int, armor_type: String) -> Array[int]:
    var amounts: Array[int] = []
    for i in range(max(0, purchase_count)):
        var current_level: int = start_level + i
        if current_level <= 0:
            continue
        var amount: int = 0
        match armor_type:
            "enemy":
                amount = int(pow(4, current_level))
            "boss":
                amount = int(25 * pow(4, current_level - 1))
            _:
                amount = int(pow(3, current_level))
        amounts.append(amount)
    return amounts

func _join_int_list(values: Array[int]) -> String:
    if values.is_empty():
        return "0"
    var text_values: PackedStringArray = []
    for value in values:
        text_values.append(str(value))
    if text_values.size() == 1:
        return text_values[0]
    if text_values.size() == 2:
        return "%s and %s" % [text_values[0], text_values[1]]
    var last_value: String = text_values[text_values.size() - 1]
    text_values.remove_at(text_values.size() - 1)
    return "%s, and %s" % [", ".join(text_values), last_value]

func _humanize_name(name_text: String) -> String:
    var text: String = name_text.strip_edges()
    if text == "":
        return "Upgrade"
    text = text.to_lower().replace("_", " ")
    var words: PackedStringArray = text.split(" ", false)
    for i in range(words.size()):
        if words[i].length() <= 0:
            continue
        words[i] = words[i].substr(0, 1).to_upper() + words[i].substr(1)
    return " ".join(words)

func _resolve_icon(node: Dictionary) -> String:
    var raw_icon: String = str(node.get("icon", "")).strip_edges()
    if raw_icon != "" and raw_icon != "?":
        return raw_icon
    return _fallback_icon_for_key(str(node.get("key", "")))

func _fallback_icon_for_key(key: String) -> String:
    var lower: String = key.to_lower()
    if lower.begins_with("core_"):
        return "C"
    if lower.begins_with("extra_skill_"):
        var family: String = _extra_skill_family(lower)
        match family:
            "ECON":
                return "E"
            "DENS":
                return "D"
            "SURV":
                return "S"
            "MOVE":
                return "M"
            "POWR":
                return "P"
            "ACTV":
                return "A"
            "BOSS":
                return "B"
            _:
                return "T"
    if lower.begins_with("recruit_"):
        return "H"
    if lower.find("boss") != -1:
        return "B"
    if lower.find("power") != -1 or lower.find("active") != -1:
        return "P"
    if lower.find("armor") != -1 or lower.find("plate") != -1 or lower.find("fortify") != -1:
        return "S"
    if lower.find("drop") != -1 or lower.find("coin") != -1 or lower.find("salvage") != -1 or lower.find("magnet") != -1:
        return "E"
    if lower.find("damage") != -1 or lower.find("speed") != -1:
        return "D"
    var fallback: String = lower.strip_edges()
    if fallback == "":
        return "U"
    return fallback.substr(0, 1).to_upper()

func _extra_skill_name(key: String) -> String:
    var n: int = int(key.trim_prefix("extra_skill_"))
    if n <= 0:
        return "Extra Skill"
    var idx: int = (n - 1) % EXTRA_NAME_A.size()
    return "%s %s %d" % [EXTRA_NAME_A[idx], EXTRA_NAME_B[idx], n]

func _core_name(key: String, level: int = 1) -> String:
    if key == "core_armor":
        return "Core Armor"
    if key.begins_with("core_armor_enemy_"):
        var track: int = int(key.trim_prefix("core_armor_enemy_"))
        return "Contact Armor " + _roman(track)
    if key.begins_with("core_armor_dot_"):
        var track: int = int(key.trim_prefix("core_armor_dot_"))
        return "DoT Armor " + _roman(track)
    if key.begins_with("core_armor_boss_"):
        var track: int = int(key.trim_prefix("core_armor_boss_"))
        return "Boss Armor " + _roman(track)
    if key == "core_density":
        return "Core Density"
    if key == "core_drop":
        return "Core Drop"
    if key == "core_power":
        return "Core Power"
    var hero_name: String = _hero_core_name(key)
    if hero_name != "":
        var node_tier: String = _roman(_hero_core_node_index(level) + 1)
        if key.find("damage") != -1:
            return "%s Damage %s" % [hero_name, node_tier]
        if key.find("speed") != -1:
            return "%s Speed %s" % [hero_name, node_tier]
    if key.find("knight") != -1 and key.find("damage") != -1:
        return "Core Knight Damage"
    if key.find("knight") != -1 and key.find("speed") != -1:
        return "Core Knight Speed"
    if key.find("knight") != -1 and key.find("active_cap") != -1:
        return "Core Knight Active Cap"
    if key.find("archer") != -1 and key.find("damage") != -1:
        return "Core Archer Damage"
    if key.find("archer") != -1 and key.find("speed") != -1:
        return "Core Archer Speed"
    if key.find("archer") != -1 and key.find("active_cap") != -1:
        return "Core Archer Active Cap"
    if key.find("guardian") != -1 and key.find("damage") != -1:
        return "Core Guardian Damage"
    if key.find("guardian") != -1 and key.find("speed") != -1:
        return "Core Guardian Speed"
    if key.find("guardian") != -1 and key.find("active_cap") != -1:
        return "Core Guardian Active Cap"
    if key.find("mage") != -1 and key.find("damage") != -1:
        return "Core Mage Damage"
    if key.find("mage") != -1 and key.find("speed") != -1:
        return "Core Mage Speed"
    if key.find("mage") != -1 and key.find("active_cap") != -1:
        return "Core Mage Active Cap"
    return _humanize_name(key)

func _hero_core_name(key: String) -> String:
    if key.find("knight") != -1:
        return "Knight"
    if key.find("archer") != -1:
        return "Archer"
    if key.find("guardian") != -1:
        return "Guardian"
    if key.find("mage") != -1:
        return "Mage"
    return ""

func _hero_core_node_index(level: int) -> int:
    return clampi((max(level, 1) - 1) / HERO_CORE_TIERS_PER_NODE, 0, HERO_DAMAGE_NODE_PCT.size() - 1)

func _roman(value: int) -> String:
    match value:
        1:
            return "I"
        2:
            return "II"
        3:
            return "III"
        4:
            return "IV"
        5:
            return "V"
        6:
            return "VI"
        7:
            return "VII"
        8:
            return "VIII"
        9:
            return "IX"
        10:
            return "X"
        _:
            return str(value)
