extends Node
class_name Mods

var bool_types: Array[Util.MODS] = [

]


var percent_mods: Array[Util.MODS] = [
    Util.MODS.ASTEROID_DENSITY, 
    Util.MODS.PLANET_DENSITY, 

    Util.MODS.CLICK_AOE, 
    Util.MODS.CLICK_RATE, 
    Util.MODS.CHANCE_TO_RESPAWN_ASTEROID_ON_BREAK, 
    Util.MODS.CHANCE_TO_ADD_TIME_ON_ASTEROID_DESTROYED, 

    Util.MODS.ASTEROIDS_PERCENT_TO_RESPAWN_ON_BLACK_HOLE_GROW, 
    Util.MODS.CHANCE_TO_SPAWN_SPECIAL_ASTEROID_ELECTRIC, 
    Util.MODS.CHANCE_TO_SPAWN_SPECIAL_ASTEROID_RADIOACTIVE, 
    Util.MODS.SPECIAL_ASTEROID_BOMB_SCALE, 
    Util.MODS.SPECIAL_ASTEROID_CHANCE_TO_FORK, 
    Util.MODS.SPECIAL_ASTEROID_CHAIN_DISTANCE_SCALE, 
    Util.MODS.SPECIAL_ASTEROID_RADIOACTIVE_AOE_SCALE, 

    Util.MODS.CLICKER_CRIT_CHANCE, 
    Util.MODS.CLICKER_CRIT_BONUS, 

    Util.MODS.ELECTRIC_CRIT_CHANCE, 
    Util.MODS.ELECTRIC_CRIT_BONUS, 

    Util.MODS.SPECIAL_PLANET_MOON_SPAWN_CHANCE, 
    Util.MODS.SPECIAL_PLANET_MOON_CLIKCER_RATE_BUFF_SCALE, 
    Util.MODS.SPECIAL_PLANET_MOON_CLIKCER_AOE_BUFF_SCALE, 

    Util.MODS.COMET_AOE_SPAWN_CHANCE, 
    Util.MODS.COMET_CLICKER_AOE_BUFF_DURATION, 
    Util.MODS.COMET_MONEY_SPAWN_CHANCE, 
    Util.MODS.COMET_MONEY_BUFF_AMOUNT, 
    Util.MODS.COMET_CRIT_CHANCE_SPAWN_CHANCE, 
    Util.MODS.COMET_CRIT_CHANCE_BUFF_SCALE, 
    Util.MODS.COMET_CRIT_BONUS_DAMAGE_BUFF_SCALE, 
    Util.MODS.COMET_SPAWN_CHANCE, 

    Util.MODS.SPECIAL_PLANET_CHANCE_TO_SPAWN_FROZEN, 
    Util.MODS.SPECIAL_PLANET_FROZEN_SHARD_DISTANCE_SCALE, 

    Util.MODS.CHANCE_TO_ADD_TIME_ON_PLANET_DESTROYED, 
    Util.MODS.PLANET_PERCENT_TO_RESPAWN_ON_BLACK_HOLE_GROW, 
    Util.MODS.CHANCE_TO_RESPAWN_PLANET_ON_BREAK, 

    Util.MODS.CHANCE_TO_SPAWN_SPECIAL_ASTEROID_GOLDEN, 
    Util.MODS.SPECIAL_ASTEROID_GOLDEN_BONUS_MONEY_SCALE, 
    Util.MODS.SPECIAL_ASTEROID_GOLDEN_CRIT_CHANCE, 
    Util.MODS.SPECIAL_ASTEROID_GOLDEN_CRIT_BONUS_MONEY_SCALE, 
    Util.MODS.COMET_CHANCE_FOR_COMET_SHOWER, 

    Util.MODS.LASER_WIDTH_SCALE, 
    Util.MODS.LASER_CRIT_CHANCE, 
    Util.MODS.LASER_CRIT_BONUS, 
    Util.MODS.SPECIAL_STAR_LASER_SPAWN_CHANCE, 

    Util.MODS.SPECIAL_STAR_SUPERNOVA_SPAWN_CHANCE, 
    Util.MODS.SUPERNOVA_DAMAGE_PERCENT_CURRENT_HEALTH, 
    Util.MODS.SUPERNOVA_RADIUS_SCALE, 

    Util.MODS.SPECIAL_STAR_FIREBALL_SPAWN_CHANCE, 
    Util.MODS.FIREBALL_CHAIN_DISTANCE_SCALE, 
    Util.MODS.CHANCE_TO_RESPAWN_STAR_ON_BREAK, 
    Util.MODS.CHANCE_TO_ADD_TIME_ON_STAR_DESTROYED, 
    Util.MODS.STAR_PERCENT_TO_RESPAWN_ON_BLACK_HOLE_GROW, 
    Util.MODS.STAR_DENSITY, 

    Util.MODS.SPECIAL_STAR_CHANCET_TO_SPAWN_ELECTRIC, 
    Util.MODS.SPECIAL_STAR_CHANCE_TO_FORK, 
    Util.MODS.SPECIAL_STAR_CHAIN_DISTANCE_SCALE, 
    Util.MODS.SPECIAL_STAR_ELECTRIC_CRIT_CHANCE, 
    Util.MODS.SPECIAL_STAR_ELECTRIC_CRIT_BONUS, 

]

var percent_mods_zero: Array[Util.MODS] = [
    Util.MODS.ASTEROID_DENSITY, 
    Util.MODS.PLANET_DENSITY, 
    Util.MODS.STAR_DENSITY, 
    ]


var dict = {
    Util.MODS.PASSIVE_MONEY_PER_SECOND: 0.0, 
    Util.MODS.MONEY_PER_MATTER: 1.0, 

    Util.MODS.CLICK_AOE: 1.0, 
    Util.MODS.CLICK_RATE: 1.0, 
    Util.MODS.BASE_DAMAGE_PER_CLICK: 1.0, 

    Util.MODS.MAX_ASTEROID_SIZE: 1.0, 

    Util.MODS.RUN_TIMER_AMOUNT_ON_BLACK_HOLE_GROW: 0.0, 
    Util.MODS.RUN_TIMER_BASE: 12.0, 

    Util.MODS.CHANCE_TO_ADD_TIME_ON_ASTEROID_DESTROYED: 0.0, 
    Util.MODS.RUN_TIMER_AMOUNT_ON_ASTEROID_DESTROYED: 0.1, 


    Util.MODS.ASTEROID_DENSITY: 1.0, 

    Util.MODS.ASTEROIDS_PERCENT_TO_RESPAWN_ON_BLACK_HOLE_GROW: 0.0, 
    Util.MODS.CHANCE_TO_RESPAWN_ASTEROID_ON_BREAK: 0.0, 


    Util.MODS.SPECIAL_ASTEROID_BOMB_DAMAGE: 1, 
    Util.MODS.SPECIAL_ASTEROID_BOMB_SCALE: 1.0, 


    Util.MODS.CHANCE_TO_SPAWN_SPECIAL_ASTEROID_ELECTRIC: 0.0, 
    Util.MODS.SPECIAL_ASTEROID_ELECTRIC_DAMAGE: 1.0, 
    Util.MODS.SPECIAL_ASTEROID_ELECTRIC_MAX_CHAINS: 3, 
    Util.MODS.SPECIAL_ASTEROID_CHANCE_TO_FORK: 0.0, 
    Util.MODS.SPECIAL_ASTEROID_CHAIN_DISTANCE_SCALE: 1.0, 


    Util.MODS.CHANCE_TO_SPAWN_SPECIAL_ASTEROID_RADIOACTIVE: 0.0, 
    Util.MODS.SPECIAL_ASTEROID_RADIOACTIVE_DOT: 1.0, 
    Util.MODS.SPECIAL_ASTEROID_RADIOACTIVE_DURATION: 5.0, 
    Util.MODS.SPECIAL_ASTEROID_RADIOACTIVE_AOE_SCALE: 1.0, 

    Util.MODS.CLICKER_CRIT_CHANCE: 0.0, 
    Util.MODS.CLICKER_CRIT_BONUS: 2.0, 

    Util.MODS.ELECTRIC_CRIT_CHANCE: 0.0, 
    Util.MODS.ELECTRIC_CRIT_BONUS: 2.0, 

    Util.MODS.BLACK_HOLE_MAX_SIZE: 10, 
    Util.MODS.PLANET_DENSITY: 0.0, 
    Util.MODS.CLICKER_BONUS_DAMAGE_TO_PLANETS: 0.0, 



    Util.MODS.MAX_PLANET_SIZE: 1.0, 

    Util.MODS.SPECIAL_PLANET_MOON_SPAWN_CHANCE: 0.0, 
    Util.MODS.SPECIAL_PLANET_MOON_MAX_MOONS: 1.0, 
    Util.MODS.SPECIAL_PLANET_MOON_CLIKCER_RATE_BUFF_SCALE: 0.1, 
    Util.MODS.SPECIAL_PLANET_MOON_CLIKCER_AOE_BUFF_SCALE: 0.1, 
    Util.MODS.SPECIAL_PLANET_MOON_BUFF_DURATION: 3.0, 
    Util.MODS.MOON_LIMIT_HARD_CAP: 10.0, 

    Util.MODS.BONUS_MONEY_SCALE: 0.0, 

    Util.MODS.COMET_SPAWN_CHANCE: 0.0, 
    Util.MODS.COMET_MAX_NUMBER_TO_SPAWN: 1.0, 

    Util.MODS.COMET_CHANCE_FOR_COMET_SHOWER: 0.0, 
    Util.MODS.COMET_SHOWER_SIZE: 10.0, 

    Util.MODS.COMET_CRIT_CHANCE_BUFF_DURATION: 3.0, 
    Util.MODS.COMET_CRIT_CHANCE_BUFF_SCALE: 1.0, 
    Util.MODS.COMET_CRIT_BONUS_DAMAGE_BUFF_SCALE: 0.5, 

    Util.MODS.STARTING_BLACK_HOLE_LEVEL: 0.0, 

    Util.MODS.SPECIAL_PLANET_CHANCE_TO_SPAWN_FROZEN: 0.0, 
    Util.MODS.SPECIAL_PLANET_FROZEN_SHARD_MAX_DAMAGE: 50.0, 
    Util.MODS.SPECIAL_PLANET_FROZEN_SHARD_AMOUNT: 1.0, 
    Util.MODS.SPECIAL_PLANET_FROZEN_SHARD_DISTANCE_SCALE: 1.0, 

    Util.MODS.CHANCE_TO_ADD_TIME_ON_PLANET_DESTROYED: 0.0, 
    Util.MODS.RUN_TIMER_AMOUNT_ON_PLANET_DESTROYED: 0.1, 
    Util.MODS.PLANET_PERCENT_TO_RESPAWN_ON_BLACK_HOLE_GROW: 0.0, 
    Util.MODS.CHANCE_TO_RESPAWN_PLANET_ON_BREAK: 0.0, 

    Util.MODS.SPECIAL_PLANET_ASTEROID_PINATA_SPAWN_CHANCE: 0.0, 
    Util.MODS.SPECIAL_PLANET_ASTEROID_PINATA_AMOUNT_OF_ASTEROID: 6.0, 


    Util.MODS.UFO_ELECTRIC_CHARGES_TO_ADD: 3, 
    Util.MODS.UFO_SPAWN_CHANCE: 0.0, 
    Util.MODS.UFO_MAX_NUMBER_TO_SPAWN: 1, 

    Util.MODS.CHANCE_TO_SPAWN_SPECIAL_ASTEROID_GOLDEN: 0.0, 
    Util.MODS.SPECIAL_ASTEROID_GOLDEN_BONUS_MONEY_SCALE: 0.5, 
    Util.MODS.SPECIAL_ASTEROID_GOLDEN_CRIT_CHANCE: 0.0, 
    Util.MODS.SPECIAL_ASTEROID_GOLDEN_CRIT_BONUS_MONEY_SCALE: 1.0, 


    Util.MODS.CLICK_RATE_BUFF: 0.0, 
    Util.MODS.CLICK_AOE_BUFF: 0.0, 
    Util.MODS.CLICKER_CRIT_CHANCE_BUFF: 0.0, 
    Util.MODS.CLICKER_CRIT_BONUS_BUFF: 0.0, 


    Util.MODS.STAR_DENSITY: 1.0, 
    Util.MODS.CLICKER_BONUS_DAMAGE_TO_STAR: 0.0, 
    Util.MODS.MAX_STAR_SIZE: 1.0, 
    Util.MODS.CHANCE_TO_ADD_TIME_ON_STAR_DESTROYED: 0.0, 
    Util.MODS.RUN_TIMER_AMOUNT_ON_STAR_DESTROYED: 0.1, 
    Util.MODS.STAR_PERCENT_TO_RESPAWN_ON_BLACK_HOLE_GROW: 0.0, 
    Util.MODS.CHANCE_TO_RESPAWN_STAR_ON_BREAK: 0.0, 

    Util.MODS.LASER_DAMAGE: 2000.0, 
    Util.MODS.LASER_WIDTH_SCALE: 1.0, 
    Util.MODS.LASER_CRIT_CHANCE: 0.0, 
    Util.MODS.LASER_CRIT_BONUS: 2.0, 
    Util.MODS.SPECIAL_STAR_LASER_SPAWN_CHANCE: 0.0, 

    Util.MODS.SPECIAL_STAR_SUPERNOVA_SPAWN_CHANCE: 0.0, 
    Util.MODS.SUPERNOVA_DAMAGE_PERCENT_CURRENT_HEALTH: 0.2, 
    Util.MODS.SUPERNOVA_RADIUS_SCALE: 1.0, 


    Util.MODS.SPECIAL_STAR_FIREBALL_SPAWN_CHANCE: 0.0, 
    Util.MODS.SPECIAL_STAR_MAX_FIREBALLS: 10.0, 
    Util.MODS.FIREBALL_DAMAGE: 500.0, 
    Util.MODS.FIREBALL_MAX_CHAINS: 5.0, 
    Util.MODS.FIREBALL_CHAIN_DISTANCE_SCALE: 1.0, 



    Util.MODS.SPECIAL_STAR_CHANCET_TO_SPAWN_ELECTRIC: 0.0, 
    Util.MODS.SPECIAL_STAR_ELECTRIC_DAMAGE: 1800.0, 
    Util.MODS.SPECIAL_STAR_ELECTRIC_MAX_CHAINS: 5, 
    Util.MODS.SPECIAL_STAR_CHANCE_TO_FORK: 0.0, 
    Util.MODS.SPECIAL_STAR_CHAIN_DISTANCE_SCALE: 10.0, 
    Util.MODS.SPECIAL_STAR_ELECTRIC_CRIT_CHANCE: 0.0, 
    Util.MODS.SPECIAL_STAR_ELECTRIC_CRIT_BONUS: 2.0, 


    Util.MODS.ASTEROIDS_TO_SPAWN: 20.0, 
    Util.MODS.NUMBER_OF_ASTEROIDS_INTO_PLANETS: 0, 
    Util.MODS.NUMBER_OF_PLANETS_INTO_STARS: 0, 

    Util.MODS.PLANETS_TO_SPAWN: 0, 
    Util.MODS.STARS_TO_SPAWN: 0, 
    Util.MODS.CLICKER_ELECTRIC_CLICKS_TO_START_WITH: 0, 



}


func get_mod(mod_type: Util.MODS):
    return dict.get(mod_type, null)

func set_mod(mod_type: Util.MODS, value):
    var old_value = dict[mod_type]
    dict[mod_type] = value

    SignalBus.mod_changed.emit(mod_type, old_value, value)


func change_mod(mod_type: Util.MODS, value):
    var old_value = dict[mod_type]
    if mod_type in bool_types:
        dict[mod_type] = value
    else:
        dict[mod_type] += value

    SignalBus.mod_changed.emit(mod_type, old_value, dict[mod_type])























func get_from_to(mod_type: Util.MODS, value):
    var s = ""
    var current = get_mod(mod_type)
    if mod_type in bool_types:
        s = "{FROM} to {TO}".format({
            "FROM": "Enabled" if current else "Disabled", 
            "TO": "Enabled" if value else "Disabled"
        })
    elif mod_type in percent_mods:
        s = "{FROM}% to {TO}%".format({
            "FROM": str(snapped(100 * current, 1)), 
            "TO": str(snapped(100 * (value + current), 1)), 
        })
    else:
        s = "{FROM} to {TO}".format({
            "FROM": str(int(get_mod(mod_type))), 
            "TO": str(int(value + current)), 
        })

    return s


func get_mod_value(mod_type: Util.MODS, value, show_plus = false):
    var s = ""

    if mod_type in bool_types:
        s = "Enabled" if value else "Disabled"
    elif mod_type in percent_mods:
        s = "{PLUS}{VALUE}%".format({
            "VALUE": str(snapped(100 * value, 1)), 
            "PLUS": "+" if show_plus else ""
        })
    else:
        s = "{PLUS}{VALUE}".format({
            "VALUE": str(int(value)), 
            "PLUS": "+" if show_plus else ""
        })

    return s
